APP/Areas/Main/Controllers/BookController.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Models;
using Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Utility;

namespace APP.Areas.Main.Controllers
{

    [Area("Main")]
    [Authorize(Roles = SD.RoleAdmin)]
    public class BookController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<BookController> _logger;
        public readonly IWebHostEnvironment _hostEnvironment;
        public BookController(ILogger<BookController> logger, IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
            _unitOfWork = unitOfWork;
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult SetQty()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Books books)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = await _unitOfWork.BeginTransactionAsync())
                {
                    try
                    {
                        string webRootPath = _hostEnvironment.WebRootPath;
                        var files = HttpContext.Request.Form.Files;
                        if (files.Count > 0)
                        {
                            string fileName = Guid.NewGuid().ToString();
                            var uploads = Path.Combine(webRootPath, @"img\book");
                            var extenstion = Path.GetExtension(files[0].FileName);

                            //if (books.ImgUrl != null)
                            //{
                            //    //this is an edit and we need to remove old image
                            //    var imagePath = Path.Combine(webRootPath, books.ImgUrl.TrimStart('\\'));
                            //    if (System.IO.File.Exists(imagePath))
                            //    {
                            //        System.IO.File.Delete(imagePath);
                            //    }
                            //}

                            using (var filesStreams = new FileStream(Path.Combine(uploads, fileName + extenstion), FileMode.Create))
                            {
                                files[0].CopyTo(filesStreams);
                            }
                            books.ImgUrl = @"\img\book\" + fileName + extenstion;
                        }
                        var book = new Books()
                        {
                            ImgUrl = books.ImgUrl,
                            Author = books.Author,
                            ISBN = books.ISBN,
                            Name = books.Name,
                            Price = books.Price,
                            Description=books.Description

                        };
                         await _unitOfWork.Books.AddAsync(book);
                         _unitOfWork.SaveAsync();
                        _unitOfWork.CommitAsync(transaction);
                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception)
                    {
                        _unitOfWork.RollbackAsync(transaction);
                        return StatusCode(StatusCodes.Status500InternalServerError);
                    }
                    
                }
            }

            return View(books);
        }
    
        public async Task<IActionResult>AddQty (string id)
        {
            var book= await _unitOfWork.Books.GetFirstOrDefaultAsync(a => a.Id == Convert.ToInt32(id));
            if (book == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddQty(Books books)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = await _unitOfWork.BeginTransactionAsync())
                {
                    try
                    {
                        var book = await _unitOfWork.Books.GetFirstOrDefaultAsync(a => a.Id == books.Id);


                        book.Qty = books.Qty;
                        _unitOfWork.SaveAsync();
                        _unitOfWork.CommitAsync(transaction);
                        return RedirectToAction(nameof(SetQty));
                    }
                    catch (Exception)
                    {
                        _unitOfWork.RollbackAsync(transaction);
                        return StatusCode(StatusCodes.Status500InternalServerError);
                    }

                }
            }

            return View(books);
        }
        public async Task<IActionResult> EditBook(string id)
        {
            var book = await _unitOfWork.Books.GetFirstOrDefaultAsync(a => a.Id == Convert.ToInt32(id));
            if (book == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditBook(Books books)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = await _unitOfWork.BeginTransactionAsync())
                {
                    try
                    {
                        string webRootPath = _hostEnvironment.WebRootPath;
                        var files = HttpContext.Request.Form.Files;
                        if (files.Count > 0)
                        {
                            string fileName = Guid.NewGuid().ToString();
                            var uploads = Path.Combine(webRootPath, @"img\book");
                            var extenstion = Path.GetExtension(files[0].FileName);

                            if (books.ImgUrl != null)
                            {
                                
                                var imagePath = Path.Combine(webRootPath, books.ImgUrl.TrimStart('\\'));
                                if (System.IO.File.Exists(imagePath))
                                {
                                    System.IO.File.Delete(imagePath);
                                }
                            }
                            using (var filesStreams = new FileStream(Path.Combine(uploads, fileName + extenstion), FileMode.Create))
                            {
                                files[0].CopyTo(filesStreams);
                            }
                            books.ImgUrl = @"\img\book\" + fileName + extenstion;
                        }
                        var book = await _unitOfWork.Books.GetFirstOrDefaultAsync(a => a.Id == books.Id);

                        book.ImgUrl = books.ImgUrl;
                        book.Author = books.Author;
                        book.ISBN = books.ISBN;
                        book.Name = books.Name;
                        book.Price = books.Price;
                        book.Description = books.Description;
                        _unitOfWork.SaveAsync();
                        _unitOfWork.CommitAsync(transaction);
                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception)
                    {
                        _unitOfWork.RollbackAsync(transaction);
                        return StatusCode(StatusCodes.Status500InternalServerError);
                    }

                }
            }

            return View(books);
        }

        public async Task<IActionResult> ViewBook(string id)
        {
            var book = await _unitOfWork.Books.GetFirstOrDefaultAsync(a => a.Id == Convert.ToInt32(id));
            if (book == null)
            {
                return RedirectToAction(nameof(Index));
            }
           
            return View(book);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ViewBook(Books books)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = await _unitOfWork.BeginTransactionAsync())
                {
                    try
                    {
                        
                        var book = await _unitOfWork.Books.GetFirstOrDefaultAsync(a => a.Id == books.Id);

                      
                        book.CurStatus = book.CurStatus==SD.Active?SD.DeActive:SD.Active;
                        _unitOfWork.SaveAsync();
                        _unitOfWork.CommitAsync(transaction);
                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception)
                    {
                        _unitOfWork.RollbackAsync(transaction);
                        return StatusCode(StatusCodes.Status500InternalServerError);
                    }

                }
            }

            return View(books);
        }

        #region Data Loads
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var objList = await _unitOfWork.Books.GetAllAsync();
            return Json(new { data = objList });
        }
       
        #endregion

    }
}

APP/Areas/Main/Controllers/OrderController.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Utility;

namespace APP.Areas.Main.Controllers
{
    [Area("Main")]
    [Authorize(Roles = SD.RoleAdmin)]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<OrderController> _logger;
        public readonly IWebHostEnvironment _hostEnvironment;
        public OrderController(ILogger<OrderController> logger, IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
            _unitOfWork = unitOfWork;
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult PayOrder()
        {
            return View();
        }
        public async Task<IActionResult> ViewOrder(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var order = await _unitOfWork.Order.GetFirstOrDefaultAsync(a => a.Id == Convert.ToInt32(id),includeProperties:"User");
                
                return View(order);
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> PayOrderRcpt(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var order = await _unitOfWork.Order.GetFirstOrDefaultAsync(a => a.Id == Convert.ToInt32(id),includeProperties:"User");
                
                return View(order);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PayOrderRcpt(Orders orders)
        {
            var ord = await _unitOfWork.Order.GetFirstOrDefaultAsync(a => a.Id == orders.Id, includeProperties: "User");
            if (ModelState.IsValid)
            {
                using (var transaction = await _unitOfWork.BeginTransactionAsync())
                {
                    try
                    {
                        ord.TotPaid = ord.TotAmount;
                        _unitOfWork.SaveAsync();
                        _unitOfWork.CommitAsync(transaction);
                        return RedirectToAction(nameof(PayOrder));
                    }
                    catch (Exception)
                    {
                        _unitOfWork.RollbackAsync(transaction);
                        return StatusCode(StatusCodes.Status500InternalServerError);
                    }

                }
            }

            return View(ord);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ViewOrder(Orders orders)
        {
            var ord = await _unitOfWork.Order.GetFirstOrDefaultAsync(a => a.Id == orders.Id, includeProperties: "User");
            if (ModelState.IsValid)
            {
                using (var transaction = await _unitOfWork.BeginTransactionAsync())
                {
                    try
                    {

                     
                        ord.OrderStatus = orders.OrderStatus;
                        _unitOfWork.SaveAsync();
                        _unitOfWork.CommitAsync(transaction);
                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception)
                    {
                        _unitOfWork.RollbackAsync(transaction);
                        return StatusCode(StatusCodes.Status500InternalServerError);
                    }

                }
            }

            return View(ord);
        }

        #region Data Loads
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var objList = from a in await _unitOfWork.Order.GetAllAsync(includeProperties: "User")
                          select new
                          {
                              user = a.User.UserName,
                              date = a.OrderDate,
                              totAmt= a.TotAmount,
                              paidAmt = a.TotPaid,
                              orderStatus= a.OrderStatus==SD.Delivered?"Delivered":(a.OrderStatus==SD.OnProcess?"On Process": "Pending"),
                              curStatus= a.CurStatus==SD.Active?"Active":"De-Activate",
                              a.Id
                          };
          

            var data = objList;
            return Json(new { data});
            
        }
        [HttpGet]
        public async Task<IActionResult> GetAllOrder()
        {
            var objList = from a in await _unitOfWork.Order.GetAllAsync(includeProperties: "User")
                          where a.CurStatus == SD.Active && a.TotAmount>a.TotPaid && a.OrderStatus==SD.Delivered
                          select new
                          {
                              user = a.User.UserName,
                              date = a.OrderDate,
                              totAmt = a.TotAmount,
                              paidAmt = a.TotPaid,
                              orderStatus = a.OrderStatus == SD.Delivered ? "Delivered" : (a.OrderStatus == SD.OnProcess ? "On Process" : "Pending"),
                              curStatus = a.CurStatus == SD.Active ? "Active" : "De-Activate",
                              a.Id
                          };


            var data = objList;
            return Json(new { data });

        }
        [HttpGet]
        public async Task<IActionResult> GetOrderDetailAll(string id)
        {
            var objList = from a in await _unitOfWork.OrderDetails.GetAllAsync(includeProperties: "Books")
                          where a.OrderId==Convert.ToInt32(id)
                          select new
                          {
                              url=a.Books.ImgUrl,
                              name = a.Books.Name,
                              isbn = a.Books.ISBN,
                              qty = a.Qty,
                          
                          };
            return Json(new { data = objList });
        }

        #endregion
    }
}

APP/ViewComponents/UserNameAdminViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace RuhunuFarms.ViewComponents
{
    public class UserNameViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public UserNameViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userFromDb = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(u => u.Id == claims.Value);

            return View(userFromDb);
        }
    }
}

APP/Views/Shared/_Cart.cshtml
@using APP.Session
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContext
@{
    var  session = httpContext.HttpContext.Session;
    var cart=  session.Get<List<CartDetails>>("Cart");
    int count = cart == null ? 0 : cart.Count;
    double tot = 0;
}
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <span class="lnr lnr-cart"></span>
        <span class="badge badge-bg-1">@count</span>
    </a>
    <ul class="dropdown-menu cart-list s-cate">
        @if (cart != null)
        {
            @foreach (var item in cart)
            {
                <li class="single-cart-list">
                    <a href="#" class="photo"><img src="@item.Books.ImgUrl" class="cart-thumb" alt="image" /></a>
                    <div class="cart-list-txt">
                        <h6>@item.Books.Name</h6>
                        <p>@item.Qty x - <span class="price">@item.Books.Price</span></p>
                    </div><!--/.cart-list-txt-->
                    <div class="cart-close">
                        <span class="lnr lnr-cross"></span>
                    </div><!--/.cart-close-->
                </li><!--/.single-cart-list -->
                tot = tot+ Convert.ToDouble ( item.Qty * item.Books.Price);
            }
            <li class="total">
                <span>Total: Rs.@tot</span>
                <button class="btn-cart pull-right" onclick="window.location.href='/Public/Home/ViewCart'">view cart</button>
            </li>
        }
        else
        {
            <li class="total">
                <span>Total: Rs 0.00</span>
               
            </li>
        }


    </ul>
</li><!--/.dropdown-->

APP/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" id="btnCreate" class="btn btn-success form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index" id="btnBackToList" class="btn btn-info form-control">Back to List</a>
    </div>
</div>

APP/Views/Shared/_LayoutMain.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EBook</title>
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"> 
    <link rel="stylesheet"
        href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="~/css/bundles/style.min.css">
    @await RenderSectionAsync("Styles", required: false)

<style>
    [class*=sidebar-dark-] {
        background-color: #002244;
    }
</style>
</head>


<body class="hold-transition sidebar-mini layout-fixed">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light border-bottom-0">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <partial name="_LoginPartial" />
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary">
            <!-- Brand Logo -->
            <a href="~/template/index3.html" class="brand-link border-bottom-0">
                <img src="~/template/dist/img/AdminLTELogo.png" alt="AdminLTE Logo"
                    class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light font-weight-bold">E-Book</span>
            </a>


            <!-- Sidebar -->
            <div class="sidebar text-sm">
                <!-- Sidebar user (optional) -->
                @if (SignInManager.IsSignedIn(User))
                {
                    @await Component.InvokeAsync("UserName")
                }

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->

                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Home" asp-area="Main" class="nav-link">
                                <i class="nav-icon fas fa-chalkboard-teacher"></i>
                                <p>
                                    Dashboard
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Book Manager
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Book" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Manage Books</p>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Create" asp-controller="Book" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Create Books</p>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="SetQty" asp-controller="Book" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Set Books Quantity</p>
                                    </a>
                                </li>
                            </ul>
                        </li> 
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-calendar"></i>
                                <p>
                                    Orders Manager
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Order" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Manage Order</p>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="PayOrder" asp-controller="Order" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Pay Order</p>
                                    </a>
                                </li>
                            </ul>
                           
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-receipt"></i>
                                <p>
                                    Reports Manager
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Print" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Orders</p>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Books" asp-controller="Print" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Books</p>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="ReciveAmount" asp-controller="Print" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Set Books Quantity</p>
                                    </a>
                                </li>
                            </ul> 
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="OnProcess" asp-controller="Print" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Set Books Quantity</p>
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-users"></i>
                                <p>
                                    User Manager
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="CustomerDetails" asp-controller="User" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Manage Customer</p>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="User" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Manage Users</p>
                                    </a>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                @* <div class="container-fluid">
                    <div class="row mb-2">
                    <div class="col-sm-6">
                    <h1>Blank Page</h1>
                    </div>
                    <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Blank Page</li>
                    </ol>
                    </div>
                    </div>
                    </div><!-- /.container-fluid --> *@
            </section>

            <section class="content">
                @RenderBody()
            </section>

            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        @* <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
            <b>Version</b> 3.2.0-rc
            </div>
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights
            reserved.
            </footer> *@

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <script src="~/js/bundles/script.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>